name: Pylint Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install pylint
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=./src pylint **/*.py || true
      
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: PYTHONPATH=./src pytest
